[workspace]
resolver = "2"
members = ["cli", "fsidx"]

[workspace.dependencies]
globset = "0.4.11"
nix = { version = "0.29.0", features = [ "fs", "term" ] }
serde = { version = "1.0.133", features = ["derive"] }

[patch.crates-io]
fsidx = { path = 'fsidx' }
