[package]
name = "fsidx-cli"
version = "0.1.0"
edition = "2021"
authors = ["joachim.erbs@gmx.de"]
license = "MIT"
description = "Finding file names quickly with a database."
categories = ["command-line-utilities", "filesystem"]
keywords = ["locate"]

[[bin]]
name = "fsidx"
path = "src/bin.rs"

[dependencies]
clap = "3.0.10"
fsidx = "0.1.0"
serde = { version = "1.0.133", features = ["derive"] }
toml = "0.5.8"

[dev-dependencies]
indoc = "1.0.3"
